### ISSUE TITLE
Implement merge correctly

### ISSUE THREAD

**Issue by qbx2** [ryankurte/rust-rolling-stats#2]
Using this method, we should be able to calculate correct m2 and std_dev.

https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Parallel_algorithm

**Comment by ryankurte** [comment]
seems like a good idea!

**Comment by antimora** [comment]
Here is a fresh issue ticket that I have filed with examples: https://github.com/ryankurte/rust-rolling-stats/issues/4

**Comment by ryankurte** [comment]
aand should be solved in `0.7.0`, thank for your effort @qbx2 and @antimora !

**Comment by antimora** [comment]
@ryankurte, I was inspired to release [`hstats`](https://crates.io/crates/hstats) that uses rolling-stats underneath. It's for online histogram statistics calculations. Simple tool to solve my needs. Thanks again for the library.

**Comment by qbx2** [comment]
Thanks!
