### ISSUE TITLE
Inconsistent Standard Deviation Results When Merging Stats with Different Counts

### ISSUE THREAD

**Issue by antimora** [ryankurte/rust-rolling-stats#4]
I've noticed an issue where the calculated standard deviation decreases as the number of combined statistical objects increases, which is problematic when using the parallel algorithm with Rayon. 

Here are examples to illustrate this behavior:

For 2496 combined stats, we get:

```
Stats { min: 0.0, max: 14310.888671875, mean: 3.9861050303125505, 
std_dev: 38.71869918444431, count: 54848256, mean2: 0.0 }
```

For 500 combined stats, we get:

```
Stats { min: 0.0, max: 14310.888671875, mean: 3.9861050303125514, 
std_dev: 45.776591826060944, count: 54848256, mean2: 0.0 }
```

For 9 combined stats, we get:

```
Stats { min: 0.0, max: 14310.888671875, mean: 3.9861050303125, 
std_dev: 50.78629284164707, count: 54848256, mean2: 0.0 }
```

For a single stat, we get:

```
Stats { min: 0.0, max: 14310.888671875, mean: 3.986105030312422, 
std_dev: 50.8585967353882, count: 54848256, mean2: 0.0 }
```

As you can see, the `std_dev` value decreases as the count of combined stats increases, which seems counter-intuitive. This issue could potentially affect computations when utilizing parallel algorithms with Rayon.

**Comment by antimora** [comment]
I will be submitting a PR tomorrow. I am working on this to fix it.

**Comment by ryankurte** [comment]
sounds brilliant! i have just picked this up again and run into the same problems so, will look forward to the PR ^_^

**Comment by antimora** [comment]
@ryankurte 
> sounds brilliant! i have just picked this up again and run into the same problems so, will look forward to the PR ^_^

Done and submitted: https://github.com/ryankurte/rust-rolling-stats/pull/5
